FROM php:7.4.21-fpm

RUN apt-get update && apt-get -y install wget telnet unzip libaio1 libaio-dev net-tools vim libxml2-dev libcurl4-openssl-dev pkg-config libssl-dev iputils-ping zip libzip-dev htop

ENV TZ=Europe/Madrid
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN docker-php-ext-install pdo_mysql

RUN docker-php-ext-install shmop

RUN pecl install apcu && docker-php-ext-enable apcu

RUN docker-php-ext-install opcache

RUN docker-php-ext-install zip

RUN pecl install redis && docker-php-ext-enable redis

RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer

COPY ./build/php-fpm/www.conf.interfaz /usr/local/etc/php-fpm.d/www.conf

RUN wget https://phar.phpunit.de/phpunit-6.5.phar && chmod +x phpunit-6.5.phar && mv phpunit-6.5.phar /usr/local/bin/phpunit

COPY interfaz /var/www/interfaz

WORKDIR /var/www/interfaz

RUN chmod -R 777 var
